config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/*id' => 'home#index', id: /(?!admin|settings|users|all|comment).*/

  # List:
  # - /articles
  # - /article/:id
  # - /portfolio
  # - /project/:id
  # - /contact
  # - /about
  # - some more links such as '/legal-stuff or something'

  # Whitelisted
  # - admin/*
  # - /settings.json
  # - /users/* [ users/sign_in, users/sign_out, users/sign_up]
  # - /all_articles.json | /all_projects.json

  get '/settings' => 'home#configuration', as: :configuration
  get '/admin' => 'home#admin', as: :admin
  get '/all_articles.json' => 'home#articles_index'
  get '/all_projects.json' => 'home#portfolio_index'
  post '/comment' => 'home#comment'

  devise_for :users, skip: [:password]

  scope '/admin' do

    authenticate :user do

      post '/article/:id' => 'articles#update'
    end
    devise_for :users, skip: [:sessions]

    resources :articles, only: :create do
      resources :comments
    end

    post '/articles/multiple/:actions' => 'articles#multiple_actions'
    post '/articles/:id/ajax_delete' => 'articles#ajax_delete'

    get '*path' => 'home#admin'
  end
end


=begin
 resource :basics, path: :settings
      resources :portfolios, except: %w[show new edit index update]
      get '/portfolio' => 'portfolios#index'
      get '/project/:id' => 'portfolios#show', as: :portfolio_show
      get '/new/project' => 'portfolios#new'
      get '/project/:id/edit' => 'portfolios#edit'
      post '/project/:id' => 'portfolios#update'

      


      post '/articles/multiple/:actions/:data' => 'articles#multiple_actions'
      

      post '/portfolio/multiple/:actions/:data' => 'portfolios#multiple_actions'
      post '/portfolio/:id/ajax_delete' => 'portfolios#ajax_delete'
      post '/portfolio/encode_file' => 'portfolios#encode_file'
      

=end

app/models/basic.rb
class Basic < ApplicationRecord
  has_many :social_networks
  accepts_nested_attributes_for :social_networks, reject_if: :all_blank, allow_destroy: true
  mount_uploader :logo, LogoUploader
  attr_accessor :logged_in, :user
end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController

  layout 'admin'
  before_action :set_basic, only: [:show, :edit, :update, :destroy]

  # GET /basics
  # GET /basics.json
  def index
    @basics = Basic.all
  end

  # GET /basics/1
  # GET /basics/1.json
  def show
  end

  # GET /basics/new
  def new
    @basic = Basic.new
    @basic.social_networks.build
  end

  # GET /basics/1/edit
  def edit
  end

  # POST /basics
  # POST /basics.json
  def create
    @basic = Basic.new(basic_params)

    respond_to do |format|
      if @basic.save
        format.html { redirect_to admin_path, notice: 'Basic was successfully created.' }
        format.json { render :show, status: :created, location: @basic }
      else
        format.html { render :new }
        format.json { render json: @basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basics/1
  # PATCH/PUT /basics/1.json
  def update
    respond_to do |format|
      if @basic.update(basic_params)
        format.html { redirect_to basics_path, notice: 'Basic was successfully updated.' }
        format.json { render :show, status: :ok, location: @basic }
      else
        format.html { render :edit }
        format.json { render json: @basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basics/1
  # DELETE /basics/1.json
  def destroy
    @basic.destroy
    respond_to do |format|
      format.html { redirect_to basics_url, notice: 'Basic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_basic
    @basic = Basic.first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def basic_params
    params.require(:basic).permit(:base_title, :alert, :notice, :seen, :front_page, :logo, social_networks_attributes: [:id, :name, :url])
  end
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/views/basics/_form.html.erb
<%= form_with(model: @basic, local: true, url: basics_path) do |f| %>
  <% if @basic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basic.errors.count, 'error') %> prohibited this basic from being saved:</h2>

      <ul>
      <% @basic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :base_title %>
    <%= f.text_field :base_title, id: :basic_base_title %>
  </div>

  <div class="field">
    <%= f.label :front_page %>
    <%= f.text_field :front_page %>
    <p>Portfolio, articles, résumé ou présentation</p>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo, id: :basic_logo %>
  </div>

  <div id="social_networks">
    <%= f.fields_for :social_networks do |sn| %>
      <%= render 'social_networks', f: sn %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Ajouter', f, :social_networks, :partial => 'social_networks' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basics/_social_network_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Nom' %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, placeholder: 'Lien du bordel' %>
  </div>

  <div class="links">
    <%= link_to_remove_association 'Supprimer', f %>
  </div>
</div>

app/views/basics/_social_networks.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Nom' %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, placeholder: 'Lien du bordel' %>
  </div>

  <div class="links">
    <%= link_to_remove_association 'Supprimer', f %>
  </div>
</div>

app/views/basics/edit.html.erb
<div id="basics_edit"></div>

<h1>Editing Basic</h1>

<%= render 'form', basic: @basic %>

<%= link_to 'Show', @basics %> |
<%= link_to 'Back', basics_path %>

app/views/basics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Basics</h1>

<table>
  <thead>
    <tr>
      <th>Base title</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basics.each do |basic| %>
      <tr>
        <td><%= basic.base_title %></td>
        <td><%= basic.resume %></td>
        <td><%= link_to 'Show', basic %></td>
        <td><%= link_to 'Edit', edit_basic_path(basic) %></td>
        <td><%= link_to 'Destroy', basic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basic', new_basic_path %>

app/views/basics/new.html.erb
<h1>New Basic</h1>

<%= render 'form', basic: @basic %>

<%= link_to 'Back', basics_path %>

app/views/basics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Base title:</strong>
  <%= @basic.base_title %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @basic.resume %>
</p>

<%= link_to 'Edit', edit_basics_path %> |
<%= link_to 'Back', basics_path %>